### PR TITLE
css-media-queries -- Sarah You

### PR DESCRIPTION
**Pull request by sarah-you**
https://user-images.githubusercontent.com/103456134/230280699-96ec7f1b-a352-477e-89cd-ac4a3f511718.mov

### CODE REVIEW

**Comment by sarah-you** [comment]
incomplete ** working on the viewport section

**Comment by sarah-you** [comment]
https://user-images.githubusercontent.com/103456134/230456244-68a910e5-54ee-4ea0-b0da-415da2f3ab1d.mov

**Comment by sarah-you** [comment]
[Breakpoints.mov.zip](https://github.com/sarah-you/c0323-code-solutions/files/11173213/Breakpoints.mov.zip)

**Review by shawnkost — APPROVED** [review]
👍🏻

**Pull request merged**
